### ISSUE TITLE
Documentation Quest

### ISSUE THREAD

**Issue by nrc** [tikv/sig-transaction#25]
The quest has not yet begun. Please check back here in July.

Before the quest starts:

- remove this header section
- add a 'leader board'
- add tasks
- add mentors

TiKV needs better documentation. The transaction SIG will do its part by documenting the concepts and code behind the TiKV/TiDB transaction system.

If the quest is successful, it should be easier for

* users to understand the isolation properties and performance characteristics of TiKV/TiDB
* users to reason about how to configure their transaction usage
* new contributors to understand TiKV transactions and write code to change their implementation
* outsiders to survey and understand TiKV's transaction implementation, and compare it to other databases

## Mentors

If you want advice, help, or review, the following people are available and will prioritize quest issues:

* @nrc 
* TODO

## Resources

Existing documentation and other resources are listed in the [doc](https://github.com/tikv/sig-transaction/tree/master/doc) directory.

## Tasks

To claim a task:

* file an issue for it (either in this repository or [TiKV](https://github.com/tikv/tikv)
* include a reference to this issue, and ask a mentor (listed above) to add the issue link here
* a mentor will be assigned to that issue and they will keep this issue up to date with the task's status
* let the mentor know if you need help or if someone else should take on the task

Tasks may or may not have a related issue. Tasks with names are being worked on by that user and should have an open issue for discussion. Boxes get ticked when the documentation task is complete.

### High level documentation

Describe the underlying concepts of transactions (mostly be linking to other material, but we should organize and document that material and ensure it covers everything, filling in gaps where necessary). Describe at an algorithmic level the way transactions are implemented in TiKV.

- [ ] Transactions overview, data format, latches, MVCC ([TiDB docs](https://pingcap.com/docs/stable/transaction-overview/), [TinyKV docs](https://github.com/pingcap-incubator/tinykv/blob/course/doc/project4-Transaction.md), [Xuelian's blog](https://andremouche.github.io/tidb/transaction_in_tidb.html), VLDB paper)
- [ ] Optimistic locking
- [ ] Pessimistic locking ([blog post](https://pingcap.com/blog/pessimistic-locking-better-mysql-compatibility-fewer-rollbacks-under-high-load/))
- [ ] Isolation/consistency properties ([Jepsen report](https://jepsen.io/analyses/tidb-2.1.7))
- [ ] Lock management/waiter mangement, deadlock detection
- [ ] GC, green GC
- [ ] Pipelined pessimistic locking
- [ ] Large transactions ([blog post](https://pingcap.com/blog/large-transactions-in-tidb/))
- [ ] Parallel commit ([repo](https://github.com/nrc/parcom))
- [ ] 1pc
- [ ] Replica read (aka follower read)
- [ ] Timestamps and HLC
- [ ] Alternative implementations

### Module documentation

Describe modules of the TiKV implementation. This should *how* the code works, *why* that design was chosen, and how it fits in with the larger transaction system. We should have documentation per-concept, which should be roughly a Rust module, but is unlikely to exactly match.

TODO tasks

### Code comments

Not every type and function needs a comment, but it would be great to document the more important and more complex code.

TODO tasks

**Comment by nrc** [comment]
# Leader board

User | Tasks complete
:--:|:--:
@nrc|0

**Comment by pramodbiligiri** [comment]
Noting down my thoughts on what the existing TiDB docs look like. I'm keeping in mind two types of users (Users and Developers) and the kind of documentation they'll need:
1. Users → User Guide: a step by step guide on how to use TiKV Transactions.
2. Developers → Design docs, Module level and code level docs.
3. Both Users and Developers → TiDB Transactions Reference, which is exhaustive but may not have detailed explanations.

Existing TiDB docs look like this:
Target audience | Type of docs | Current location
-- | -- | --
Users | User Guide | docs.pingcap.com -> Reference -> SQL -> [Transactions](https://docs.pingcap.com/tidb/stable/transaction-overview)
Users, Developers | Reference | docs.pingcap.com -> Reference -> SQL -> [Transactions](https://docs.pingcap.com/tidb/stable/transaction-overview)
Developers | Developer docs | [sig-transaction](https://tikv.github.io/sig-transaction/)
Existing and prospective customers | Blog posts | https://pingcap.com/blog/pessimistic-locking-better-mysql-compatibility-fewer-rollbacks-under-high-load and https://pingcap.com/blog/large-transactions-in-tidb

Blog posts are good to announce new features in a timely manner, but they are hard to discover when reading other official documentation. So any information in blogs should also be available in one of the other sources. Ideally, blog posts should contain links to more official documentation but never the other way round.

**Comment by pramodbiligiri** [comment]
Based on this, I'm planning to write up some docs within sig-transaction, because Developer docs can do with small improvements and won't affect the end user directly. Any further suggestion on which part of sig-transaction I can expand on will be welcome.

**Comment by nrc** [comment]
> Based on this, I'm planning to write up some docs within sig-transaction, because Developer docs can do with small improvements and won't affect the end user directly. 

Awsome, thank you!

> Any further suggestion on which part of sig-transaction I can expand on will be welcome

I think a good thing to do is to pick a module and add some comments on types - it is mostly possible to do that by searching for uses.
