### ISSUE TITLE
Docs quest planning

### ISSUE THREAD

**Issue by nrc** [tikv/sig-transaction#8]
I'd like a 'docs quest' to be one of the first activities for the SIG.

## Questions

* ~~How to track progress and list tasks? Tracking issue, milestone, project? In this repo or TiKV repo?~~
* How to promote? TiKV blog post, Twitter, Slack. Where else?
* ~~Who will mentor?~~
* How to manage the quest?
* Who else should be looped in? (Community/ecosystem folk? i18n?)

## Tasks

- [x] define goals
- [ ] Make the list of tasks
- [x] Prepare issue text
- [x] Prepare blog post
- [x] find existing docs
- [x] find some general resources

**Comment by nrc** [comment]
The issue: https://github.com/tikv/sig-transaction/issues/25 (WIP).

> How to track progress and list tasks? Tracking issue, milestone, project? In this repo or TiKV repo?

Tracking issue in this repo

**Comment by nrc** [comment]
Launched: https://www.ncameron.org/blog/documentation-quest/
